version: "3"

services:
    app-php:
        build: ./app-php
        depends_on:
            - serverapp
            - db_serverapp
            - prm
            - layer
            - db_prm
        volumes:
            - ./app-php/src:/var/www/html/app-php
        ports:
            - 8080:80

    serverapp:
        build: ./serverapp
        depends_on:
          - db_serverapp
        volumes:
            - ./serverapp/src:/code
        ports:
            - '8000:8000'

    db_serverapp:
        image: mysql
        volumes:
            - db_serverapp_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: serverapp
            MYSQL_ROOT_PASSWORD: password

    prm:
        build: ./prm
        depends_on:
          - db_prm
        volumes:
            - ./prm/src:/code
        ports:
            - '8002:8000'
    db_prm:
        image: mysql
        volumes:
            - db_prm_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: prm
            MYSQL_ROOT_PASSWORD: password

    layer:
        build: ./layer
        ports:
            - 8001:8001
        volumes:
            - ./layer:/app
    # adminer:
    #     depends_on:
    #         - db
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8084:8080
volumes:
    db_serverapp_data: {}
    db_prm_data: {}
