version: "3"

services:
    serverapp:
        build: ./serverapp
        volumes:
            - ./serverapp:/var/www/html
        ports:
            - '8000:80'
    layer:
        depends_on:
            - db
        build: ./layer
        ports:
            - 8001:8001
        volumes:
            - ./layer:/app
    prm:
        build: ./prm
        volumes:
            - ./prm:/var/www/html
        ports:
            - '8002:80'
    db:
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
    adminer:
        depends_on:
            - db
        image: adminer
        restart: always
        ports:
            - 8084:8080
volumes:
    db_data: {}